# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"  # Ensures support for elastic_gpu_specifications and elastic_inference_accelerator blocks
    }
  }
  required_version = ">= 1.0"
}
