# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "azurerm" {
  features {}
  subscription_id = "92bafd73-6e08-4239-acee-913bf89d5e1f"
  tenant_id       = "adaf5471-32cc-46bf-9006-156e3d62803b"
}
